package com.example.formula1.utils

import com.example.formula1.BuildConfig

const val MY_KEY = BuildConfig.MY_API_KEY
const val BASE_URL = BuildConfig.BASE_URL
const val NONE = 0
const val ANIMATION_TIME = 1500L
const val DELAY_TIME = 3000L
const val KEY_AUTH =  BuildConfig.X_API_TAG
const val PAGE_ONE = 1
const val PAGE_DRIVERS = "Drivers"
const val PAGE_STARTING_GRID = "Starting Grid"
const val PAGE_RESULT = "Result"
const val PAGE_DETAIL = "Detail"
const val PAGE_HISTORY = "History"
const val PAGE_CONSTRUCTORS = "Constructors"
const val STRING_EMPTY = ""
const val DIALOG_TITLE_ENTER_YEAR = "Enter The Year"
const val CONNECTION_TIMEOUT = 8000L
const val KEY_DRIVER_ID = "Driver ID"
const val KEY_TEAM_ID = "Team ID"
const val KEY_CAR_URL = "Car ID"
const val KEY_SEASON = "Selected Season"
const val KEY_CIRCUIT_ID = "Circuit_ID"
const val TEXT_ERROR = "Something is wrong, please try again!"
const val RB_ID = 1
const val MER_ID = 5
const val FER_ID = 3
const val MCL_ID = 2
const val ALP_ID = 13
const val ROM_ID = 18
const val AST_ID = 17
const val HAAS_ID = 14
const val TAU_ID = 7
const val WIL_ID = 12
const val RACE_TYPE_DEFAULT = "race"
const val INPUT_TIME_FORMAT = "yyyy-MM-dd'T'hh:mm:ssZ"
const val OUTPUT_TIME_FORMAT = " yyyy-MM-dd HH:mm"
const val KEY_RACING_ID = "Racing ID"
const val LAST_POSITION = 9
const val HISTORY_NUMBER_ITEM = 8
const val SCORE_P1 = 25
const val SCORE_P2 = 18
const val SCORE_P3 = 15
const val SCORE_P4 = 12
const val SCORE_P5 = 10
const val SCORE_P6 = 8
const val SCORE_P7 = 6
const val SCORE_P8 = 4
const val SCORE_P9 = 2
const val SCORE_P10 = 1
